version: '2.1'

volumes:
  peergov1.gov.io:
  peertm1.manufacturer.com:
  peertm2.manufacturer.com:
  peertf1.production.com:
  peertf2.production.com:
  peerbb1.retailer.com:
  peerbb2.retailer.com:
  peerts1.wharehouse.com:
  peerts2.wharehouse.com:
  orderer1.gov.io:

services:

  peergov1.gov.io:
    container_name: peergov1.gov.io
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peergov1.gov.io
      - CORE_PEER_ADDRESS=peergov1.gov.io:13050
      - CORE_PEER_LISTENADDRESS=0.0.0.0:13050
      - CORE_PEER_CHAINCODEADDRESS=peergov1.gov.io:13051
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:13051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peergov1.gov.io:13050
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peergov1.gov.io:13050
      - CORE_PEER_LOCALMSPID=govMSP
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/gov.io/peers/peergov1.gov.io/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/gov.io/peers/peergov1.gov.io/tls:/etc/hyperledger/fabric/tls
      - peergov1.gov.io:/var/hyperledger/production
    ports:
      - 13050:13050

  peertm1.manufacturer.com:
    container_name: peertm1.manufacturer.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peertm1.manufacturer.com
      - CORE_PEER_ADDRESS=peertm1.manufacturer.com:9050
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9050
      - CORE_PEER_CHAINCODEADDRESS=peertm1.manufacturer.com:9051
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peertm1.manufacturer.com:9080
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peertm1.manufacturer.com:9050
      - CORE_PEER_LOCALMSPID=tataMSP
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/manufacturer.com/peers/peertm1.manufacturer.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/manufacturer.com/peers/peertm1.manufacturer.com/tls:/etc/hyperledger/fabric/tls
      - peertm1.manufacturer.com:/var/hyperledger/production
    ports:
      - 9050:9050

  peertm2.manufacturer.com:
    container_name: peertm2.manufacturer.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peertm2.manufacturer.com
      - CORE_PEER_ADDRESS=peertm2.manufacturer.com:9080
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9080
      - CORE_PEER_CHAINCODEADDRESS=peertm2.manufacturer.com:9081
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9081
      - CORE_PEER_GOSSIP_BOOTSTRAP=peertm2.manufacturer.com:9050
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peertm2.manufacturer.com:9080
      - CORE_PEER_LOCALMSPID=tataMSP
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/manufacturer.com/peers/peertm2.manufacturer.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/manufacturer.com/peers/peertm2.manufacturer.com/tls:/etc/hyperledger/fabric/tls
      - peertm2.manufacturer.com:/var/hyperledger/production
    ports:
      - 9080:9080

  peertf1.production.com:
    container_name: peertf1.production.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peertf1.production.com
      - CORE_PEER_ADDRESS=peertf1.production.com:8050
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8050
      - CORE_PEER_CHAINCODEADDRESS=peertf1.production.com:8051
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peertf1.production.com:8080
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peertf1.production.com:8050
      - CORE_PEER_LOCALMSPID=teafarmMSP
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/production.com/peers/peertf1.production.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/production.com/peers/peertf1.production.com/tls:/etc/hyperledger/fabric/tls
      - peertf1.production.com:/var/hyperledger/production
    ports:
      - 8050:8050

  peertf2.production.com:
    container_name: peertf2.production.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peertf2.production.com
      - CORE_PEER_ADDRESS=peertf2.production.com:8080
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8080
      - CORE_PEER_CHAINCODEADDRESS=peertf2.production.com:8081
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8081
      - CORE_PEER_GOSSIP_BOOTSTRAP=peertf2.production.com:8050
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peertf2.production.com:8080
      - CORE_PEER_LOCALMSPID=teafarmMSP
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/production.com/peers/peertf2.production.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/production.com/peers/peertf2.production.com/tls:/etc/hyperledger/fabric/tls
      - peertf2.production.com:/var/hyperledger/production
    ports:
      - 8080:8080

  peerbb1.retailer.com:
    container_name: peerbb1.retailer.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peerbb1.retailer.com
      - CORE_PEER_ADDRESS=peerbb1.retailer.com:11050
      - CORE_PEER_LISTENADDRESS=0.0.0.0:11050
      - CORE_PEER_CHAINCODEADDRESS=peerbb1.retailer.com:11051
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:11051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peerbb1.retailer.com:11080
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peerbb1.retailer.com:11050
      - CORE_PEER_LOCALMSPID=bigbazarMSP
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/retailer.com/peers/peerbb1.retailer.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/retailer.com/peers/peerbb1.retailer.com/tls:/etc/hyperledger/fabric/tls
      - peerbb1.retailer.com:/var/hyperledger/production
    ports:
      - 11050:11050

  peerbb2.retailer.com:
    container_name: peerbb2.retailer.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peerbb2.retailer.com
      - CORE_PEER_ADDRESS=peerbb2.retailer.com:11080
      - CORE_PEER_LISTENADDRESS=0.0.0.0:11080
      - CORE_PEER_CHAINCODEADDRESS=peerbb2.retailer.com:11081
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:11081
      - CORE_PEER_GOSSIP_BOOTSTRAP=peerbb1.retailer.com:11050
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peerbb2.retailer.com:11080
      - CORE_PEER_LOCALMSPID=bigbazarMSP
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/retailer.com/peers/peerbb2.retailer.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/retailer.com/peers/peerbb2.retailer.com/tls:/etc/hyperledger/fabric/tls
      - peerbb2.retailer.com:/var/hyperledger/production
    ports:
      - 11080:11080

  peerts1.wharehouse.com:
    container_name: peerts1.wharehouse.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peerts1.wharehouse.com
      - CORE_PEER_ADDRESS=peerts1.wharehouse.com:10050
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10050
      - CORE_PEER_CHAINCODEADDRESS=peerts1.wharehouse.com:10051
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peerts1.wharehouse.com:10080
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peerts1.wharehouse.com:10050
      - CORE_PEER_LOCALMSPID=tatastoreMSP
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/wharehouse.com/peers/peerts1.wharehouse.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/wharehouse.com/peers/peerts1.wharehouse.com/tls:/etc/hyperledger/fabric/tls
      - peerts1.wharehouse.com:/var/hyperledger/production
    ports:
      - 10050:10050

  peerts2.wharehouse.com:
    container_name: peerts2.wharehouse.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peerts2.wharehouse.com
      - CORE_PEER_ADDRESS=peerts2.wharehouse.com:10080
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10080
      - CORE_PEER_CHAINCODEADDRESS=peerts2.wharehouse.com:10081
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10081
      - CORE_PEER_GOSSIP_BOOTSTRAP=peerts2.wharehouse.com:10050
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peerts2.wharehouse.com:10080
      - CORE_PEER_LOCALMSPID=tatastoreMSP
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/wharehouse.com/peers/peerts2.wharehouse.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/wharehouse.com/peers/peerts2.wharehouse.com/tls:/etc/hyperledger/fabric/tls
      - peerts2.wharehouse.com:/var/hyperledger/production
    ports:
      - 10080:10080
  
  orderer1.gov.io:
    container_name: orderer1.gov.io
    extends:
      file: peer-base.yaml
      service: orderer-base
    volumes:
      - ../channel-artefacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ../crypto-config/ordererOrganizations/gov.io/orderers/orderer1.gov.io/msp:/var/hyperledger/orderer/msp
      - ../crypto-config/ordererOrganizations/gov.io/orderers/orderer1.gov.io/tls:/var/hyperledger/orderer/tls
      - orderer:/var/hyperledger/production/orderer
    ports:
      - 7050:7050